export const MSG_ERR_DIMENSIONS_NOT_SET = 'Simulation dimensions are not set'
export const MSG_ERR_OBJECT_OUT_OF_BOUNDARIES_X_LOWER = 'Object can not be spawned: X value is lower than possible'
export const MSG_ERR_OBJECT_OUT_OF_BOUNDARIES_X_HIGHER = 'Object can not be spawned: X value is higher than possible'
export const MSG_ERR_OBJECT_OUT_OF_BOUNDARIES_Y_LOWER = 'Object can not be spawned: Y value is lower than possible'
export const MSG_ERR_OBJECT_OUT_OF_BOUNDARIES_Y_HIGHER = 'Object can not be spawned: Y value is higher than possible'
